// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmctvvruztxplirnponl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtY3R2dnJ1enR4cGxpcm5wb25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NzY3MDMsImV4cCI6MjA3MzI1MjcwM30.ZQInA3SRhymMDM0aDw2SP-76SUOxHxMQvHyYvszN-2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});